#!/usr/bin/python3

import sys
import os

env = Environment(parse_flags='-lboost_thread -lboost_system -std=c++17 -I/usr/local/include/boost -L/usr/local/lib -I..')
env['ENV']['TERM'] = os.environ['TERM']
# env.Append(CCFLAGS='-O3')
env.Append(LIBS=['pthread'])

env.Program('example_client', 'client.cpp')
env.Program('example_server', 'server.cpp')
