#!/usr/bin/python3

import sys
import os

source_files = Glob('*.cpp')

env = Environment(parse_flags='-lboost_thread.a -std=c++17')
env['ENV']['TERM'] = os.environ['TERM']
# env.Append(CCFLAGS='-O3')
env.Append(LIBS=['pthread'])

# env.Library('mylib', source_files)
env.Program('udp_client', 'udp_client.cpp')
env.Program('server', 'server.cpp')
